theme: jekyll-theme-minimal
title: "Hiroko<br>Shinnaga"
description: |
  Ph.D. in Science<br>Radio Astronomy
  
  新永 浩子
  鹿児島大学 学術研究院理工学域理学系 物理・宇宙プログラム
  〒890-0065 鹿児島市郡元 1-21-35
  電話 099-285-8960 Fax 099-285-8088

  Hiroko Shinnaga
  Department of Physics and Astronomy
  Kagoshima University
  1-21-35 Korimoto, Kagoshima 890-0065 JAPAN

logo: "/avatar.png"
show_downloads: false
